The first commit, the base part
Evancel/MyProject0602 pull request #1
Opened 2023-02-11 18:57 UTC by Evancel

2023-02-18 18:26 UTC, alekseykoshelev requested changes

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Employee.java
> +    int department;
Тут тоже нужен модификатор

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        for(int i =0; i < employee.length && (i+1)<Employee.getCounterId(); i++) {
Вот это условие можно убрать `&& (i+1)<Employee.getCounterId()`, не совсем понимаю его смысл

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Employee.java
> +    public static int getCounterId(){
Этот геттер лишний, счетчик можно никуда не возвращать

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        for(int i=0; i< employee.length && (i+1)<Employee.getCounterId(); i++) {
Это можно сделать в цикле выше, просто сделать еще одно присвоение в переменную `empWithMinSalary `. 
Вообще, можно обойтись только одной переменной типа `Employee `.

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        for(int i=0; i< employee.length && (i+1)<Employee.getCounterId(); i++){
Аналогично про условие цикла, относится ко всем циклам во всех методах

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        return sumSalary() * 1.0 / (Employee.getCounterId()-1);
В целом то верно, работать будет, но лучше использовать длину массива, вместо `Employee.getCounterId()`

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +        return sumSalary() * 1.0 / (Employee.getCounterId()-1);
Вместо умножения на 1.0 можно сделать каст, вот так `(double) sumSalary()`

2023-02-18 18:26 UTC, alekseykoshelev commented on src/Main.java
> +                for (int i=0; )
Тут код как будто не дописан)

2023-02-20 09:50 UTC, Evancel commented on src/Main.java
> +        for(int i =0; i < employee.length && (i+1)<Employee.getCounterId(); i++) {
Привет. Вот здесь я не понимаю. Если убрать условие  - получаю NullPointerException, т.к. не весь массив заполнен. Т.е. массив на 10 сотрудников, созданы - 4. Через getCounterId я получаю ид последнего созданного сотрудника и дальше не проверяю, соответственно NullPointerException уходит.

2023-02-20 10:35 UTC, Evancel commented on src/Employee.java
> +    int department;
Исправлено.

2023-02-20 10:36 UTC, Evancel commented on src/Main.java
> +        for(int i =0; i < employee.length && (i+1)<Employee.getCounterId(); i++) {
Исправлено.

2023-02-20 10:36 UTC, Evancel commented on src/Employee.java
> +    public static int getCounterId(){
Исправлено.

2023-02-20 12:19 UTC, Evancel commented on src/Main.java
> +        for(int i=0; i< employee.length && (i+1)<Employee.getCounterId(); i++) {
Исправлено.

2023-02-20 12:19 UTC, Evancel commented on src/Main.java
> +        for(int i=0; i< employee.length && (i+1)<Employee.getCounterId(); i++){
Испавлено.

2023-02-20 12:19 UTC, Evancel commented on src/Main.java
> +        return sumSalary() * 1.0 / (Employee.getCounterId()-1);
Исправлено.

2023-02-20 12:19 UTC, Evancel commented on src/Main.java
> +                for (int i=0; )
Исправлено.

2023-02-21 12:40 UTC, alekseykoshelev commented on src/Main.java
> +        for(int i =0; i < employee.length && (i+1)<Employee.getCounterId(); i++) {
Тут есть два варианта:
1) можно хранить переменную size, которая будет числом реальных сотрудников в массиве. Тут нужно учесть, чтобы массив был заполнен без пропусков, вдруг мы удалили сотрудника посередине массива.
2) можно добавить проверку на `null`, если элемент массива не `null`, то выводим его. Аналогично и в других методах. 

Вижу добавила отдельную переменную, минус такого решения, что нужно будет правильно ее обновлять, если где-то упустить этот момент, то циклы сломаются)

2023-02-22 20:34 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                if (value>0 && value <=5){
Подход интересный, но что если я захотел сотруднику присвоить зарплату 2😀

2025-06-17 11:23 UTC, merged